### ISSUE TITLE
Create CODE-OF-CONDUCT.md file

### ISSUE THREAD

**Issue by Sitanshu-AI** [DeveloperJayu/DevIncept_MKS#1]
Create a code of conduct file for people who are new to open source

**Comment by swathi-469** [comment]
I would like to work on this issue please assign this to me

**Comment by Sitanshu-AI** [comment]
No I will work on it I have raised the issue

**Comment by Sitanshu-AI** [comment]
Please assign to me

**Comment by DeveloperJayu** [comment]
Assigned to Sitanshu-AI as he raised this issue
