### ISSUE TITLE
Add Contributors Section in readme 

### ISSUE THREAD

**Issue by payaldutta** [DeveloperJayu/DevIncept_MKS#6]
I want to add a contributors section in the readme to showcase all the valuable contributors of this repository.
@DeveloperJayu  Do assign me this issue under DCP'21.
Thank You.

**Comment by DeveloperJayu** [comment]
If you really wanted to contribute under DCP'21 please contribute inside projects. this kind of contribution will not gain your knowledge. Not needed of this under DCP'21 hence issue closing...
